import "./globals.css";
import { Montserrat } from "@next/font/google";

const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <nav>
          <h1>Create Next App</h1>
          <ul>
            <li>About</li>
            <li>Sign up</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
